POST http://localhost:3005/videos
Content-Type: application/json

{
    "title": "video 2",
    "duration": "100"
} 


###

GET http://localhost:3005/videos

###
PUT http://localhost:3005/videos/905dbd03-ad84-42da-9991-2f658b560458
Content-Type: application/json

{
    "title": "video xxxx",
    "duration": "340" 
}

###

DELETE  http://localhost:3005/videos/905dbd03-ad84-42da-9991-2f658b560458